Redirect error message from custom curl function to stderr

diff --git a/bin/cf_common b/bin/cf_common
--- a/bin/cf_common
+++ b/bin/cf_common
@@ -40,9 +40,7 @@ then
                 cat $BUILDPACK_PATH/dependencies/$filename
             fi
         else
-            ## Dependency does not exist
-            echo "Expected dependency to exist but could not find it: ${1}"
-            exit 1;
+            echo "Expected dependency to exist but could not find it: ${1}" 1>&2
         fi
     }
 fi
