Format files using `make format`

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -103,16 +103,16 @@ mkdir -p "$CACHE_DIR/.heroku"
 mkdir -p .heroku
 
 # The Python installation.
-cp -R "$CACHE_DIR/.heroku/python" .heroku/ &> /dev/null || true
+cp -R "$CACHE_DIR/.heroku/python" .heroku/ &>/dev/null || true
 # A plain text file which contains the current stack being used (used for cache busting).
-cp -R "$CACHE_DIR/.heroku/python-stack" .heroku/ &> /dev/null || true
+cp -R "$CACHE_DIR/.heroku/python-stack" .heroku/ &>/dev/null || true
 # A plain text file which contains the current python version being used (used for cache busting).
-cp -R "$CACHE_DIR/.heroku/python-version" .heroku/ &> /dev/null || true
+cp -R "$CACHE_DIR/.heroku/python-version" .heroku/ &>/dev/null || true
 # A plain text file which contains the current sqlite3 version being used (used for cache busting).
-cp -R "$CACHE_DIR/.heroku/python-sqlite3-version" .heroku/ &> /dev/null || true
+cp -R "$CACHE_DIR/.heroku/python-sqlite3-version" .heroku/ &>/dev/null || true
 # "editable" installations of code repositories, via pip or pipenv.
 if [[ -d "$CACHE_DIR/.heroku/src" ]]; then
-  cp -R "$CACHE_DIR/.heroku/src" .heroku/ &> /dev/null || true
+	cp -R "$CACHE_DIR/.heroku/src" .heroku/ &>/dev/null || true
 fi
 
 # The pre_compile hook. Customers rely on this. Don't remove it.
@@ -124,47 +124,47 @@ source "${BUILDPACK_DIR}/bin/steps/hooks/pre_compile"
 # Sticky runtimes. If there was a previous build, and it used a given version of Python,
 # continue to use that version of Python in perpetuity.
 if [[ -f "$CACHE_DIR/.heroku/python-version" ]]; then
-  CACHED_PYTHON_VERSION=$(cat "$CACHE_DIR/.heroku/python-version")
+	CACHED_PYTHON_VERSION=$(cat "$CACHE_DIR/.heroku/python-version")
 fi
 
 # We didn't always record the stack version. This code is in place because of that.
 if [[ -f "$CACHE_DIR/.heroku/python-stack" ]]; then
-  CACHED_PYTHON_STACK=$(cat "$CACHE_DIR/.heroku/python-stack")
+	CACHED_PYTHON_STACK=$(cat "$CACHE_DIR/.heroku/python-stack")
 else
-  CACHED_PYTHON_STACK=$STACK
+	CACHED_PYTHON_STACK=$STACK
 fi
 
 # TODO: Move this into a new package manager handling implementation when adding Poetry support.
 # We intentionally don't mention `setup.py` here since it's being removed soon.
 if [[ ! -f requirements.txt && ! -f Pipfile && ! -f setup.py ]]; then
-  puts-warn
-  puts-warn "Error: Couldn't find any supported Python package manager files."
-  puts-warn
-  puts-warn "A Python app on Heroku must have either a 'requirements.txt' or"
-  puts-warn "'Pipfile' package manager file in the root directory of its"
-  puts-warn "source code."
-  puts-warn
-  puts-warn "Currently the root directory of your app contains:"
-  puts-warn
-  # TODO: Overhaul logging helpers so they can handle prefixing multi-line strings, and switch to them.
-  # shellcheck disable=SC2012 # Using `ls` instead of `find` is absolutely fine for this use case.
-  ls -1 --indicator-style=slash "${BUILD_DIR}" | sed 's/^/ !     /'
-  puts-warn
-  puts-warn "If your app already has a package manager file, check that it:"
-  puts-warn
-  puts-warn "1. Is in the top level directory (not a subdirectory)."
-  puts-warn "2. Has the correct spelling (the filenames are case-sensitive)."
-  puts-warn "3. Isn't listed in '.gitignore' or '.slugignore'."
-  puts-warn
-  puts-warn "Otherwise, add a package manager file to your app. If your app has"
-  puts-warn "no dependencies, then create an empty 'requirements.txt' file."
-  puts-warn
-  puts-warn "For help with using Python on Heroku, see:"
-  puts-warn "https://devcenter.heroku.com/articles/getting-started-with-python"
-  puts-warn "https://devcenter.heroku.com/articles/python-support"
-  puts-warn
-  meta_set "failure_reason" "package-manager-not-found"
-  exit 1
+	puts-warn
+	puts-warn "Error: Couldn't find any supported Python package manager files."
+	puts-warn
+	puts-warn "A Python app on Heroku must have either a 'requirements.txt' or"
+	puts-warn "'Pipfile' package manager file in the root directory of its"
+	puts-warn "source code."
+	puts-warn
+	puts-warn "Currently the root directory of your app contains:"
+	puts-warn
+	# TODO: Overhaul logging helpers so they can handle prefixing multi-line strings, and switch to them.
+	# shellcheck disable=SC2012 # Using `ls` instead of `find` is absolutely fine for this use case.
+	ls -1 --indicator-style=slash "${BUILD_DIR}" | sed 's/^/ !     /'
+	puts-warn
+	puts-warn "If your app already has a package manager file, check that it:"
+	puts-warn
+	puts-warn "1. Is in the top level directory (not a subdirectory)."
+	puts-warn "2. Has the correct spelling (the filenames are case-sensitive)."
+	puts-warn "3. Isn't listed in '.gitignore' or '.slugignore'."
+	puts-warn
+	puts-warn "Otherwise, add a package manager file to your app. If your app has"
+	puts-warn "no dependencies, then create an empty 'requirements.txt' file."
+	puts-warn
+	puts-warn "For help with using Python on Heroku, see:"
+	puts-warn "https://devcenter.heroku.com/articles/getting-started-with-python"
+	puts-warn "https://devcenter.heroku.com/articles/python-support"
+	puts-warn
+	meta_set "failure_reason" "package-manager-not-found"
+	exit 1
 fi
 
 # Pipenv Python version support.
@@ -173,21 +173,21 @@ fi
 source "${BUILDPACK_DIR}/bin/steps/pipenv-python-version"
 
 if [[ -f runtime.txt ]]; then
-  # PYTHON_VERSION_SOURCE may have already been set by the pipenv-python-version step.
-  # TODO: Refactor this and stop pipenv-python-version using runtime.txt as an API.
-  PYTHON_VERSION_SOURCE=${PYTHON_VERSION_SOURCE:-"runtime.txt"}
-  puts-step "Using Python version specified in ${PYTHON_VERSION_SOURCE}"
-  meta_set "python_version_reason" "specified"
+	# PYTHON_VERSION_SOURCE may have already been set by the pipenv-python-version step.
+	# TODO: Refactor this and stop pipenv-python-version using runtime.txt as an API.
+	PYTHON_VERSION_SOURCE=${PYTHON_VERSION_SOURCE:-"runtime.txt"}
+	puts-step "Using Python version specified in ${PYTHON_VERSION_SOURCE}"
+	meta_set "python_version_reason" "specified"
 elif [[ -n "${CACHED_PYTHON_VERSION:-}" ]]; then
-  puts-step "No Python version was specified. Using the same version as the last build: ${CACHED_PYTHON_VERSION}"
-  echo "       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes"
-  meta_set "python_version_reason" "cached"
-  echo "${CACHED_PYTHON_VERSION}" > runtime.txt
+	puts-step "No Python version was specified. Using the same version as the last build: ${CACHED_PYTHON_VERSION}"
+	echo "       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes"
+	meta_set "python_version_reason" "cached"
+	echo "${CACHED_PYTHON_VERSION}" >runtime.txt
 else
-  puts-step "No Python version was specified. Using the buildpack default: ${DEFAULT_PYTHON_VERSION}"
-  echo "       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes"
-  meta_set "python_version_reason" "default"
-  echo "${DEFAULT_PYTHON_VERSION}" > runtime.txt
+	puts-step "No Python version was specified. Using the buildpack default: ${DEFAULT_PYTHON_VERSION}"
+	echo "       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes"
+	meta_set "python_version_reason" "default"
+	echo "${DEFAULT_PYTHON_VERSION}" >runtime.txt
 fi
 
 # Create the directory for .profile.d, if it doesn't exist.
@@ -201,11 +201,11 @@ mkdir -p /app/.heroku/src
 # This is (hopefully obviously) because apps end up running from `/app` in production.
 # Realpath is used to support use-cases where one of the locations is a symlink to the other.
 if [[ "$(realpath "${BUILD_DIR}")" != "$(realpath /app)" ]]; then
-    # python expects to reside in /app, so set up symlinks
-    # we will not remove these later so subsequent buildpacks can still invoke it
-    ln -nsf "$BUILD_DIR/.heroku/python" /app/.heroku/python
-    ln -nsf "$BUILD_DIR/.heroku/vendor" /app/.heroku/vendor
-    # Note: .heroku/src is copied in later.
+	# python expects to reside in /app, so set up symlinks
+	# we will not remove these later so subsequent buildpacks can still invoke it
+	ln -nsf "$BUILD_DIR/.heroku/python" /app/.heroku/python
+	ln -nsf "$BUILD_DIR/.heroku/vendor" /app/.heroku/vendor
+	# Note: .heroku/src is copied in later.
 fi
 
 # Download / Install Python, from pre-build binaries available on Amazon S3.
@@ -221,10 +221,10 @@ source "${BUILDPACK_DIR}/bin/steps/pipenv"
 # This allows for people to ship a setup.py application to Heroku
 
 if [[ ! -f requirements.txt ]] && [[ ! -f Pipfile ]]; then
-  meta_set "setup_py_only" "true"
-  echo "-e ." > requirements.txt
+	meta_set "setup_py_only" "true"
+	echo "-e ." >requirements.txt
 else
-  meta_set "setup_py_only" "false"
+	meta_set "setup_py_only" "false"
 fi
 
 # SQLite3 support.
@@ -251,10 +251,9 @@ meta_time "nltk_downloader_duration" "${nltk_downloader_start_time}"
 # In CI, $BUILD_DIR is /app.
 # Realpath is used to support use-cases where one of the locations is a symlink to the other.
 if [[ "$(realpath "${BUILD_DIR}")" != "$(realpath /app)" ]]; then
-  rm -rf "$BUILD_DIR/.heroku/src"
-  deep-cp /app/.heroku/src "$BUILD_DIR/.heroku/src"
+	rm -rf "$BUILD_DIR/.heroku/src"
+	deep-cp /app/.heroku/src "$BUILD_DIR/.heroku/src"
 fi
-
 
 # Django collectstatic support.
 # The buildpack automatically runs collectstatic for Django applications.
@@ -264,7 +263,6 @@ fi
 collectstatic_start_time=$(nowms)
 sub_env "${BUILDPACK_DIR}/bin/steps/collectstatic"
 meta_time "django_collectstatic_duration" "${collectstatic_start_time}"
-
 
 # Programmatically create .profile.d script for application runtime environment variables.
 
@@ -286,7 +284,7 @@ set_default_env PYTHONPATH "\$HOME"
 
 # Python expects to be in /app, if at runtime, it is not, set
 # up symlinks… this can occur when the subdir buildpack is used.
-cat <<EOT >> "$PROFILE_PATH"
+cat <<EOT >>"$PROFILE_PATH"
 if [[ \$HOME != "/app" ]]; then
     mkdir -p /app/.heroku
     ln -nsf "\$HOME/.heroku/python" /app/.heroku/python
@@ -298,7 +296,7 @@ EOT
 # (such as `/tmp/build_<hash>`) back to `/app`. This is not done during the build itself, since later
 # buildpacks still need the build time paths.
 if [[ "${BUILD_DIR}" != "/app" ]]; then
-  cat <<EOT >> "$PROFILE_PATH"
+	cat <<EOT >>"$PROFILE_PATH"
 find .heroku/python/lib/python*/site-packages/ -type f -and \( -name '*.egg-link' -or -name '*.pth' -or -name '__editable___*_finder.py' \) -exec sed -i -e 's#${BUILD_DIR}#/app#' {} \+
 EOT
 fi
@@ -320,9 +318,9 @@ rm -rf "$CACHE_DIR/.heroku/src"
 mkdir -p "$CACHE_DIR/.heroku"
 cp -R .heroku/python "$CACHE_DIR/.heroku/"
 cp -R .heroku/python-version "$CACHE_DIR/.heroku/"
-cp -R .heroku/python-stack "$CACHE_DIR/.heroku/" &> /dev/null || true
+cp -R .heroku/python-stack "$CACHE_DIR/.heroku/" &>/dev/null || true
 if [[ -d .heroku/src ]]; then
-  cp -R .heroku/src "$CACHE_DIR/.heroku/" &> /dev/null || true
+	cp -R .heroku/src "$CACHE_DIR/.heroku/" &>/dev/null || true
 fi
 
 meta_time "total_duration" "${compile_start_time}"
diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -7,51 +7,51 @@ PYTHON_VERSION="${PYTHON_VERSION##+([[:space:]])}"
 PYTHON_VERSION="${PYTHON_VERSION%%+([[:space:]])}"
 
 function eol_python_version_error() {
-  local major_version="${1}"
-  local eol_date="${2}"
-  puts-warn
-  puts-warn "Python ${major_version} reached upstream end-of-life on ${eol_date}, and is"
-  puts-warn "therefore no longer receiving security updates:"
-  puts-warn "https://devguide.python.org/versions/#supported-versions"
-  puts-warn
-  puts-warn "As such, it is no longer supported by this buildpack."
-  puts-warn
-  puts-warn "Please upgrade to a newer Python version."
-  puts-warn
-  puts-warn "For a list of the supported Python versions, see:"
-  puts-warn "https://devcenter.heroku.com/articles/python-support#supported-runtimes"
-  puts-warn
-  meta_set "failure_reason" "python-version-eol"
-  exit 1
+	local major_version="${1}"
+	local eol_date="${2}"
+	puts-warn
+	puts-warn "Python ${major_version} reached upstream end-of-life on ${eol_date}, and is"
+	puts-warn "therefore no longer receiving security updates:"
+	puts-warn "https://devguide.python.org/versions/#supported-versions"
+	puts-warn
+	puts-warn "As such, it is no longer supported by this buildpack."
+	puts-warn
+	puts-warn "Please upgrade to a newer Python version."
+	puts-warn
+	puts-warn "For a list of the supported Python versions, see:"
+	puts-warn "https://devcenter.heroku.com/articles/python-support#supported-runtimes"
+	puts-warn
+	meta_set "failure_reason" "python-version-eol"
+	exit 1
 }
 
 # We check for EOL prior to checking if the archive exists on S3, to ensure the more specific EOL error
 # message is still shown for newer stacks where the EOL Python versions might not have been built.
 case "${PYTHON_VERSION}" in
-  python-3.7.+([0-9]))
-    eol_python_version_error "3.7" "June 27th, 2023"
-    ;;
-  python-3.6.+([0-9]))
-    eol_python_version_error "3.6" "December 23rd, 2021"
-    ;;
-  *) ;;
+	python-3.7.+([0-9]))
+		eol_python_version_error "3.7" "June 27th, 2023"
+		;;
+	python-3.6.+([0-9]))
+		eol_python_version_error "3.6" "December 23rd, 2021"
+		;;
+	*) ;;
 esac
 
 # The Python runtime archive filename is of form: 'python-X.Y.Z-ubuntu-22.04-amd64.tar.zst'
 # The Ubuntu version is calculated from `STACK` since it's faster than calling `lsb_release`.
-UBUNTU_VERSION="${STACK/heroku-}.04"
+UBUNTU_VERSION="${STACK/heroku-/}.04"
 ARCH=$(dpkg --print-architecture)
 PYTHON_URL="${S3_BASE_URL}/${PYTHON_VERSION}-ubuntu-${UBUNTU_VERSION}-${ARCH}.tar.zst"
 
 if ! curl --output /dev/null --silent --head --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}"; then
-  puts-warn
-  puts-warn "Requested runtime '${PYTHON_VERSION}' is not available for this stack (${STACK})."
-  puts-warn
-  puts-warn "For a list of the supported Python versions, see:"
-  puts-warn "https://devcenter.heroku.com/articles/python-support#supported-runtimes"
-  puts-warn
-  meta_set "failure_reason" "python-version-not-found"
-  exit 1
+	puts-warn
+	puts-warn "Requested runtime '${PYTHON_VERSION}' is not available for this stack (${STACK})."
+	puts-warn
+	puts-warn "For a list of the supported Python versions, see:"
+	puts-warn "https://devcenter.heroku.com/articles/python-support#supported-runtimes"
+	puts-warn
+	meta_set "failure_reason" "python-version-not-found"
+	exit 1
 fi
 
 # TODO: Refactor Python version usage to use the non-prefixed form everywhere.
@@ -60,109 +60,109 @@ meta_set "python_version" "${python_version_without_prefix}"
 meta_set "python_version_major" "${python_version_without_prefix%.*}"
 
 function warn_if_patch_update_available() {
-  local requested_version="${1}"
-  local latest_patch_version="${2}"
-  # Extract the patch version component of the version strings (ie: the '5' in '3.10.5').
-  local requested_patch_number="${requested_version##*.}"
-  local latest_patch_number="${latest_patch_version##*.}"
-  if (( requested_patch_number < latest_patch_number )); then
-    puts-warn
-    puts-warn "A Python security update is available! Upgrade as soon as possible to: ${latest_patch_version}"
-    puts-warn "See: https://devcenter.heroku.com/articles/python-runtimes"
-    puts-warn
-  fi
+	local requested_version="${1}"
+	local latest_patch_version="${2}"
+	# Extract the patch version component of the version strings (ie: the '5' in '3.10.5').
+	local requested_patch_number="${requested_version##*.}"
+	local latest_patch_number="${latest_patch_version##*.}"
+	if ((requested_patch_number < latest_patch_number)); then
+		puts-warn
+		puts-warn "A Python security update is available! Upgrade as soon as possible to: ${latest_patch_version}"
+		puts-warn "See: https://devcenter.heroku.com/articles/python-runtimes"
+		puts-warn
+	fi
 }
 
 # We wait until now to display outdated Python version warnings, since we only want to show them
 # if there weren't any errors with the version to avoid adding noise to the error messages.
 case "${PYTHON_VERSION}" in
-  python-3.12.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_312}"
-    ;;
-  python-3.11.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_311}"
-    ;;
-  python-3.10.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_310}"
-    ;;
-  python-3.9.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_39}"
-    ;;
-  python-3.8.*)
-    puts-warn
-    puts-warn "Python 3.8 will reach its upstream end-of-life in October 2024, at which"
-    puts-warn "point it will no longer receive security updates:"
-    puts-warn "https://devguide.python.org/versions/#supported-versions"
-    puts-warn
-    puts-warn "Support for Python 3.8 will be removed from this buildpack on December 4th, 2024."
-    puts-warn
-    puts-warn "Upgrade to a newer Python version as soon as possible to keep your app secure."
-    puts-warn "See: https://devcenter.heroku.com/articles/python-runtimes"
-    puts-warn
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_38}"
-    ;;
-  # TODO: Make this case an error, since it should be unreachable.
-  *) ;;
+	python-3.12.*)
+		warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_312}"
+		;;
+	python-3.11.*)
+		warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_311}"
+		;;
+	python-3.10.*)
+		warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_310}"
+		;;
+	python-3.9.*)
+		warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_39}"
+		;;
+	python-3.8.*)
+		puts-warn
+		puts-warn "Python 3.8 will reach its upstream end-of-life in October 2024, at which"
+		puts-warn "point it will no longer receive security updates:"
+		puts-warn "https://devguide.python.org/versions/#supported-versions"
+		puts-warn
+		puts-warn "Support for Python 3.8 will be removed from this buildpack on December 4th, 2024."
+		puts-warn
+		puts-warn "Upgrade to a newer Python version as soon as possible to keep your app secure."
+		puts-warn "See: https://devcenter.heroku.com/articles/python-runtimes"
+		puts-warn
+		warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_38}"
+		;;
+	# TODO: Make this case an error, since it should be unreachable.
+	*) ;;
 esac
 
 if [[ "$STACK" != "$CACHED_PYTHON_STACK" ]]; then
-    puts-step "Stack has changed from $CACHED_PYTHON_STACK to $STACK, clearing cache"
-    rm -rf .heroku/python-stack .heroku/python-version .heroku/python .heroku/vendor .heroku/python .heroku/python-sqlite3-version
+	puts-step "Stack has changed from $CACHED_PYTHON_STACK to $STACK, clearing cache"
+	rm -rf .heroku/python-stack .heroku/python-version .heroku/python .heroku/vendor .heroku/python .heroku/python-sqlite3-version
 fi
 
 if [[ -f .heroku/python-version ]]; then
-  if [[ ! "$(cat .heroku/python-version)" == "$PYTHON_VERSION" ]]; then
-      puts-step "Python version has changed from $(cat .heroku/python-version) to ${PYTHON_VERSION}, clearing cache"
-      rm -rf .heroku/python
-  else
-    SKIP_INSTALL=1
-  fi
+	if [[ ! "$(cat .heroku/python-version)" == "$PYTHON_VERSION" ]]; then
+		puts-step "Python version has changed from $(cat .heroku/python-version) to ${PYTHON_VERSION}, clearing cache"
+		rm -rf .heroku/python
+	else
+		SKIP_INSTALL=1
+	fi
 fi
 
 # If using Pip, check if we should reinstall python dependencies given that requirements.txt
 # is non-deterministic (not all packages pinned, doesn't handle uninstalls etc). We don't need
 # to do this when using Pipenv, since it has a lockfile and syncs the packages for us.
 if [[ -f "${BUILD_DIR}/requirements.txt" ]]; then
-  if [[ ! -f "$CACHE_DIR/.heroku/requirements.txt" ]]; then
-    # This is a the first build of an app (or the build cache was cleared). Since there
-    # are no cached packages, we only need to store the requirements file for next time.
-    cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
-  else
-    # IF there IS a cached directory, check for differences with the new one
-    if ! diff "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt" &> /dev/null; then
-      puts-step "Requirements file has been changed, clearing cached dependencies"
-      # if there are any differences, clear the Python cache
-      # Installing Python over again does not take noticably more time
-      cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
-      rm -rf .heroku/python
-      unset SKIP_INSTALL
-    else
-      puts-step "No change in requirements detected, installing from cache"
-    fi
-  fi
+	if [[ ! -f "$CACHE_DIR/.heroku/requirements.txt" ]]; then
+		# This is a the first build of an app (or the build cache was cleared). Since there
+		# are no cached packages, we only need to store the requirements file for next time.
+		cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
+	else
+		# IF there IS a cached directory, check for differences with the new one
+		if ! diff "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt" &>/dev/null; then
+			puts-step "Requirements file has been changed, clearing cached dependencies"
+			# if there are any differences, clear the Python cache
+			# Installing Python over again does not take noticably more time
+			cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
+			rm -rf .heroku/python
+			unset SKIP_INSTALL
+		else
+			puts-step "No change in requirements detected, installing from cache"
+		fi
+	fi
 fi
 
 if [[ -n "${SKIP_INSTALL}" ]]; then
-  puts-step "Using cached install of ${PYTHON_VERSION}"
+	puts-step "Using cached install of ${PYTHON_VERSION}"
 else
-  puts-step "Installing ${PYTHON_VERSION}"
+	puts-step "Installing ${PYTHON_VERSION}"
 
-  # Prepare destination directory.
-  mkdir -p .heroku/python
+	# Prepare destination directory.
+	mkdir -p .heroku/python
 
-  if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar --zstd --extract --directory .heroku/python; then
-    # The Python version was confirmed to exist previously, so any failure here is due to
-    # a networking issue or archive/buildpack bug rather than the runtime not existing.
-    puts-warn "Failed to download/install ${PYTHON_VERSION}"
-    meta_set "failure_reason" "python-download"
-    exit 1
-  fi
+	if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 10 "${PYTHON_URL}" | tar --zstd --extract --directory .heroku/python; then
+		# The Python version was confirmed to exist previously, so any failure here is due to
+		# a networking issue or archive/buildpack bug rather than the runtime not existing.
+		puts-warn "Failed to download/install ${PYTHON_VERSION}"
+		meta_set "failure_reason" "python-download"
+		exit 1
+	fi
 
-  # Record for future reference.
-  echo "$PYTHON_VERSION" > .heroku/python-version
-  echo "$STACK" > .heroku/python-stack
+	# Record for future reference.
+	echo "$PYTHON_VERSION" >.heroku/python-version
+	echo "$STACK" >.heroku/python-stack
 
-  hash -r
+	hash -r
 fi
 
 PIP_VERSION=$(get_requirement_version 'pip')
@@ -186,12 +186,12 @@ BUNDLED_PIP_WHEEL_LIST=(.heroku/python/lib/python*/ensurepip/_bundled/pip-*.whl)
 BUNDLED_PIP_WHEEL="${BUNDLED_PIP_WHEEL_LIST[0]}"
 
 if [[ -z "${BUNDLED_PIP_WHEEL}" ]]; then
-  puts-warn "Failed to locate the bundled pip wheel"
-  meta_set "failure_reason" "bundled-pip-not-found"
-  exit 1
+	puts-warn "Failed to locate the bundled pip wheel"
+	meta_set "failure_reason" "bundled-pip-not-found"
+	exit 1
 fi
 
 /app/.heroku/python/bin/python "${BUNDLED_PIP_WHEEL}/pip" install --quiet --disable-pip-version-check --no-cache-dir \
-  "pip==${PIP_VERSION}" "setuptools==${SETUPTOOLS_VERSION}" "wheel==${WHEEL_VERSION}"
+	"pip==${PIP_VERSION}" "setuptools==${SETUPTOOLS_VERSION}" "wheel==${WHEEL_VERSION}"
 
 hash -r
diff --git a/bin/steps/sqlite3 b/bin/steps/sqlite3
--- a/bin/steps/sqlite3
+++ b/bin/steps/sqlite3
@@ -4,77 +4,77 @@
 # and the APT buildpack should be used if an app needs the sqlite CLI/headers.
 
 sqlite3_install() {
-  HEROKU_PYTHON_DIR="$1"
-  HEADERS_ONLY="$3"
+	HEROKU_PYTHON_DIR="$1"
+	HEADERS_ONLY="$3"
 
-  mkdir -p "$HEROKU_PYTHON_DIR"
+	mkdir -p "$HEROKU_PYTHON_DIR"
 
-  APT_CACHE_DIR="$HEROKU_PYTHON_DIR/apt/cache"
-  APT_STATE_DIR="$HEROKU_PYTHON_DIR/apt/state"
+	APT_CACHE_DIR="$HEROKU_PYTHON_DIR/apt/cache"
+	APT_STATE_DIR="$HEROKU_PYTHON_DIR/apt/state"
 
-  mkdir -p "$APT_CACHE_DIR/archives/partial"
-  mkdir -p "$APT_STATE_DIR/lists/partial"
+	mkdir -p "$APT_CACHE_DIR/archives/partial"
+	mkdir -p "$APT_STATE_DIR/lists/partial"
 
-  APT_OPTIONS=(
-    "--option=debug::nolocking=true"
-    "--option=dir::cache=${APT_CACHE_DIR}"
-    "--option=dir::state=${APT_STATE_DIR}"
-    "--option=dir::etc::sourcelist=/etc/apt/sources.list"
-  )
+	APT_OPTIONS=(
+		"--option=debug::nolocking=true"
+		"--option=dir::cache=${APT_CACHE_DIR}"
+		"--option=dir::state=${APT_STATE_DIR}"
+		"--option=dir::etc::sourcelist=/etc/apt/sources.list"
+	)
 
-  apt-get "${APT_OPTIONS[@]}" update > /dev/null 2>&1
-  if [[ -z "$HEADERS_ONLY" ]]; then
-    apt-get "${APT_OPTIONS[@]}" -y -d --reinstall install libsqlite3-dev sqlite3 > /dev/null 2>&1
-  else
-    apt-get "${APT_OPTIONS[@]}" -y -d --reinstall install libsqlite3-dev
-  fi
+	apt-get "${APT_OPTIONS[@]}" update >/dev/null 2>&1
+	if [[ -z "$HEADERS_ONLY" ]]; then
+		apt-get "${APT_OPTIONS[@]}" -y -d --reinstall install libsqlite3-dev sqlite3 >/dev/null 2>&1
+	else
+		apt-get "${APT_OPTIONS[@]}" -y -d --reinstall install libsqlite3-dev
+	fi
 
-  find "$APT_CACHE_DIR/archives/" -name "*.deb" -exec dpkg -x {} "$HEROKU_PYTHON_DIR/sqlite3/" \;
+	find "$APT_CACHE_DIR/archives/" -name "*.deb" -exec dpkg -x {} "$HEROKU_PYTHON_DIR/sqlite3/" \;
 
-  mkdir -p "$HEROKU_PYTHON_DIR/include"
-  mkdir -p "$HEROKU_PYTHON_DIR/lib"
+	mkdir -p "$HEROKU_PYTHON_DIR/include"
+	mkdir -p "$HEROKU_PYTHON_DIR/lib"
 
-  # remove old sqlite3 libraries/binaries
-  find "$HEROKU_PYTHON_DIR/include/" -name "sqlite3*.h" -exec rm -f {} \;
-  find "$HEROKU_PYTHON_DIR/lib/" -name "libsqlite3.*" -exec rm -f {} \;
-  rm -f "$HEROKU_PYTHON_DIR/lib/pkgconfig/sqlite3.pc"
-  rm -f "$HEROKU_PYTHON_DIR/bin/sqlite3"
+	# remove old sqlite3 libraries/binaries
+	find "$HEROKU_PYTHON_DIR/include/" -name "sqlite3*.h" -exec rm -f {} \;
+	find "$HEROKU_PYTHON_DIR/lib/" -name "libsqlite3.*" -exec rm -f {} \;
+	rm -f "$HEROKU_PYTHON_DIR/lib/pkgconfig/sqlite3.pc"
+	rm -f "$HEROKU_PYTHON_DIR/bin/sqlite3"
 
-  # eg: `x86_64` or `aarch64`
-  GNU_ARCH=$(arch)
+	# eg: `x86_64` or `aarch64`
+	GNU_ARCH=$(arch)
 
-  # copy over sqlite3 headers & bins and setup linking against the stack image library
-  mv "$HEROKU_PYTHON_DIR/sqlite3/usr/include/"* "$HEROKU_PYTHON_DIR/include/"
-  mv "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu"/libsqlite3.*a "$HEROKU_PYTHON_DIR/lib/"
-  mkdir -p "$HEROKU_PYTHON_DIR/lib/pkgconfig"
-  # set the right prefix/lib directories
-  sed -e 's/prefix=\/usr/prefix=\/app\/.heroku\/python/' -e "s/\/${GNU_ARCH}-linux-gnu//" "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu/pkgconfig/sqlite3.pc" > "$HEROKU_PYTHON_DIR/lib/pkgconfig/sqlite3.pc"
-  # need to point the libsqlite3.so to the stack image library for /usr/bin/ld -lsqlite3
-  SQLITE3_LIBFILE="/usr/lib/${GNU_ARCH}-linux-gnu/$(readlink -n "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu/libsqlite3.so")"
-  ln -s "$SQLITE3_LIBFILE" "$HEROKU_PYTHON_DIR/lib/libsqlite3.so"
-  if [[ -z "$HEADERS_ONLY" ]]; then
-    mv "$HEROKU_PYTHON_DIR/sqlite3/usr/bin"/* "$HEROKU_PYTHON_DIR/bin/"
-  fi
+	# copy over sqlite3 headers & bins and setup linking against the stack image library
+	mv "$HEROKU_PYTHON_DIR/sqlite3/usr/include/"* "$HEROKU_PYTHON_DIR/include/"
+	mv "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu"/libsqlite3.*a "$HEROKU_PYTHON_DIR/lib/"
+	mkdir -p "$HEROKU_PYTHON_DIR/lib/pkgconfig"
+	# set the right prefix/lib directories
+	sed -e 's/prefix=\/usr/prefix=\/app\/.heroku\/python/' -e "s/\/${GNU_ARCH}-linux-gnu//" "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu/pkgconfig/sqlite3.pc" >"$HEROKU_PYTHON_DIR/lib/pkgconfig/sqlite3.pc"
+	# need to point the libsqlite3.so to the stack image library for /usr/bin/ld -lsqlite3
+	SQLITE3_LIBFILE="/usr/lib/${GNU_ARCH}-linux-gnu/$(readlink -n "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu/libsqlite3.so")"
+	ln -s "$SQLITE3_LIBFILE" "$HEROKU_PYTHON_DIR/lib/libsqlite3.so"
+	if [[ -z "$HEADERS_ONLY" ]]; then
+		mv "$HEROKU_PYTHON_DIR/sqlite3/usr/bin"/* "$HEROKU_PYTHON_DIR/bin/"
+	fi
 
-  # cleanup
-  rm -rf "$HEROKU_PYTHON_DIR/sqlite3/"
-  rm -rf "$HEROKU_PYTHON_DIR/apt/"
+	# cleanup
+	rm -rf "$HEROKU_PYTHON_DIR/sqlite3/"
+	rm -rf "$HEROKU_PYTHON_DIR/apt/"
 }
 
 buildpack_sqlite3_install() {
-  puts-step "Installing SQLite3"
+	puts-step "Installing SQLite3"
 
-  # TODO: This never actual prints failure or even aborts the build, since
-  # the conditional disables `set -e` inside the called function:
-  # https://stackoverflow.com/q/19789102
-  # ...plus whoever wrote this forgot the `exit 1` in the `else` anyway.
-  if sqlite3_install "$BUILD_DIR/.heroku/python" ; then
-    # mcount "success.python.sqlite3"
-    :
-  else
-    echo "Sqlite3 failed to install."
-    # mcount "failure.python.sqlite3"
-  fi
+	# TODO: This never actual prints failure or even aborts the build, since
+	# the conditional disables `set -e` inside the called function:
+	# https://stackoverflow.com/q/19789102
+	# ...plus whoever wrote this forgot the `exit 1` in the `else` anyway.
+	if sqlite3_install "$BUILD_DIR/.heroku/python"; then
+		# mcount "success.python.sqlite3"
+		:
+	else
+		echo "Sqlite3 failed to install."
+		# mcount "failure.python.sqlite3"
+	fi
 
-  mkdir -p "$CACHE_DIR/.heroku/"
+	mkdir -p "$CACHE_DIR/.heroku/"
 }
