Improve detection error messages (#1608)
Previously if an app was missing the necessary Python package manager
files, buildpack detection would fail with the generic error message
provided by the build system (see previous version of test fixtures for
an example).

This error message required users to click through to the Dev Center
documentation to find out what files need to be present for a Python app
to work on Heroku, and there are quite a few support tickets where users
have struggled to resolve this themselves (see GUS work item for ticket
links).

Now a custom error message is displayed, similar to what the Node.js and
PHP buildpacks do:
https://github.com/heroku/heroku-buildpack-nodejs/blob/main/bin/detect
https://github.com/heroku/heroku-buildpack-php/blob/main/bin/detect

This error message lists some common reasons why the files might not be
found (such as them not being in the root directory), and also prints a
directory listing of the root directory to help the user (and support)
understand what is happening.

Lastly, the detection logic has been made more permissive, so that
Python apps that are missing some of the required files (but have other
misc Python related files) still pass detection, allowing us to perform
the stricter file check during the build phase instead. This is
particularly important for the "new app with no buildpacks set" case,
where in the case of buildpack detect failure a custom detect error
message is not shown by the build system (since it's not viable to show
the custom message from half a dozen language buildpacks
simultaneously), but a build phase error message is.

These changes also bring the classic Python buildpack more in line with
the Python CNB implementation:
https://github.com/heroku/buildpacks-python/blob/447c7dd978bc3069fb1baa0005a83e4720ba1e63/src/detect.rs#L4-L25
https://github.com/heroku/buildpacks-python/blob/447c7dd978bc3069fb1baa0005a83e4720ba1e63/src/errors.rs#L71-L81

GUS-W-7924407.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -134,6 +134,39 @@ else
   CACHED_PYTHON_STACK=$STACK
 fi
 
+# TODO: Move this into a new package manager handling implementation when adding Poetry support.
+# We intentionally don't mention `setup.py` here since it's being removed soon.
+if [[ ! -f requirements.txt && ! -f Pipfile && ! -f setup.py ]]; then
+  puts-warn
+  puts-warn "Error: Couldn't find any supported Python package manager files."
+  puts-warn
+  puts-warn "A Python app on Heroku must have either a 'requirements.txt' or"
+  puts-warn "'Pipfile' package manager file in the root directory of its"
+  puts-warn "source code."
+  puts-warn
+  puts-warn "Currently the root directory of your app contains:"
+  puts-warn
+  # TODO: Overhaul logging helpers so they can handle prefixing multi-line strings, and switch to them.
+  # shellcheck disable=SC2012 # Using `ls` instead of `find` is absolutely fine for this use case.
+  ls -1 --indicator-style=slash "${BUILD_DIR}" | sed 's/^/ !     /'
+  puts-warn
+  puts-warn "If your app already has a package manager file, check that it:"
+  puts-warn
+  puts-warn "1. Is in the top level directory (not a subdirectory)."
+  puts-warn "2. Has the correct spelling (the filenames are case-sensitive)."
+  puts-warn "3. Isn't listed in '.gitignore' or '.slugignore'."
+  puts-warn
+  puts-warn "Otherwise, add a package manager file to your app. If your app has"
+  puts-warn "no dependencies, then create an empty 'requirements.txt' file."
+  puts-warn
+  puts-warn "For help with using Python on Heroku, see:"
+  puts-warn "https://devcenter.heroku.com/articles/getting-started-with-python"
+  puts-warn "https://devcenter.heroku.com/articles/python-support"
+  puts-warn
+  meta_set "failure_reason" "package-manager-not-found"
+  exit 1
+fi
+
 # Pipenv Python version support.
 # Detect the version of Python requested from a Pipfile (e.g. python_version or python_full_version).
 # Convert it to a runtime.txt file.
