abort if bad python requested

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -140,6 +140,12 @@ fi
 if [ ! "$SKIP_INSTALL" ]; then
   puts-step "Preparing Python runtime ($PYTHON_VERSION)"
   curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx > /dev/null
+  if [[ $rc != 0 ]] ; then
+    puts-warn "Requested runtime ($PYTHON_VERSION) was not found. More info:"
+    puts-warn "https://devcenter.heroku.com/articles/python-support"
+    puts-warn "Aborting."
+    exit 1
+  fi
   mv python .heroku/python
 
   # Record for future reference.
