Verify the checksums of packages downloaded from AWS
With pip 8, the integrity of packages downloaded from PyPI during the
buildpack compile can be ensured by adding hashes to the requirements
files. However until now there was no guarantee that the python and/or
library packages downloaded from AWS were had not been tampered with
themselves.

Whilst the downloads are performed over HTTPS, also verifying the hash
of the downloaded archives protects against:
* S3 bucket compromise
* CA miss-issuance of an s3.amazonaws.com cert
* Protocol or client exploits (Qualys site rating for S3 is only a "B")
* Non-malicious modification of existing files (eg uploading a newer
  Python version over an older one)

In the case of checksum mismatches, the compile will now be aborted.

For now, if a known checksum is not found for the downloaded file, then
only a warning is output. This will prevent breakage if there are any
runtimes or stacks uploaded to S3 that are not mentioned in this repo.
In the future we may want to make this cause the compile to fail.

The existing checksums were generated via a script run on a cedar-14
dyno (see the PR).

diff --git a/bin/utils b/bin/utils
--- a/bin/utils
+++ b/bin/utils
@@ -95,6 +95,19 @@ download-unpack() {
 
   curl $URL --silent --fail --retry 5 --retry-max-time 15 -o $FILENAME || return 1
 
+  grep -s -e "  $FILENAME\$" $CHECKSUMS_FILE | sha256sum --check --strict > /dev/null 2>&1
+
+  # Both statuses have to be assigned in one command, or PIPESTATUS will be overwritten.
+  GREP_STATUS="${PIPESTATUS[0]}" SHASUM_STATUS="${PIPESTATUS[1]}"
+
+  if [[ $GREP_STATUS != 0 ]] ; then
+    # TODO: Make this fatal in the future, once we're confident no checksums are missing.
+    puts-warn "Skipping verification of $FILENAME - no known checksum found!"
+  elif [[ $SHASUM_STATUS != 0 ]] ; then
+    puts-warn "Downloaded file $FILENAME did not have the expected checksum. Aborting!"
+    exit 1
+  fi
+
   cd $WORKING_DIR
   tar xzf $TMP_DOWNLOAD_DIR/$FILENAME -C $TARGET_DIR &> /dev/null
 }
