Fix parsing of DISABLE_COLLECTSTATIC env var values (#1208)
By default if Django is installed and a `manage.py` file found, the
buildpack will run Django's `collectstatic` command at the end of the
build.

This step can be skipped by setting `DISABLE_COLLECTSTATIC=1`:
https://devcenter.heroku.com/articles/django-assets#disabling-collectstatic

However previously, if `DISABLE_COLLECTSTATIC` was instead set to `0` or
the empty string (such as when toggling it on and off during debugging),
then collectstatic would still be skipped.

This behaviour was made more confusing due to there being no build output
that explained why collectstatic was being skipped.

Now:
* Using values of `0` or the empty string are treated the same as if
  `DISABLE_COLLECTSTATIC` was not set at all (all other values are
  unaffected).
* If `collectstatic` is skipped (either due to that env var, the legacy
  skip file, or because a `manage.py` file is not found), then the build
  output now contains the reason why.
* A deprecation warning is output when collectstatic is skipped via the
  legacy `.heroku/collectstatic_disabled` file method.

I've also added some more tests around collectstatic, since there was
only one before, and refactored the collectstatic step script to use
early returns for improved readability.

See:
https://heroku.support/950668
https://heroku.support/986549

Closes GUS-W-8813947.

diff --git a/bin/steps/collectstatic b/bin/steps/collectstatic
--- a/bin/steps/collectstatic
+++ b/bin/steps/collectstatic
@@ -13,75 +13,83 @@
 # shellcheck source=bin/utils
 source "$BIN_DIR/utils"
 
+if [[ -f .heroku/collectstatic_disabled ]]; then
+  puts-step "Skipping Django collectstatic since the file '.heroku/collectstatic_disabled' exists."
+  puts-warn "This approach is deprecated, please set the env var DISABLE_COLLECTSTATIC=1 instead."
+  mcount "warnings.collectstatic_disabled_file"
+  mcount "django.collectstatic.disabled"
+  exit 0
+fi
+
+if [[ "${DISABLE_COLLECTSTATIC:-0}" != "0" ]]; then
+  puts-step "Skipping Django collectstatic since the env var DISABLE_COLLECTSTATIC is set."
+  mcount "django.collectstatic.disabled"
+  exit 0
+fi
+
+# Ensure that Django is actually installed.
+if ! is_module_available 'django'; then
+  exit 0
+fi
+
 # Location of 'manage.py', if it exists.
 MANAGE_FILE=$(find . -maxdepth 3 -type f -name 'manage.py' -printf '%d\t%P\n' | sort -nk1 | cut -f2 | head -1)
 MANAGE_FILE=${MANAGE_FILE:-fakepath}
 
-# Legacy file-based support for $DISABLE_COLLECTSTATIC
-[ -f .heroku/collectstatic_disabled ] && DISABLE_COLLECTSTATIC=1
-
-# Ensure that Django is actually installed.
-is_module_available 'django' && DJANGO_INSTALLED=1
-
-
-if [ ! "$DISABLE_COLLECTSTATIC" ] && [ -f "$MANAGE_FILE" ] && [ "$DJANGO_INSTALLED" ]; then
-    set +e
-
-    puts-step "$ python $MANAGE_FILE collectstatic --noinput"
-
-    # Run collectstatic, cleanup some of the noisy output.
-    PYTHONPATH=${PYTHONPATH:-.}
-    export PYTHONPATH
-
-    # Create a temporary file for collecting the collectstaic logs.
-    COLLECTSTATIC_LOG=$(mktemp)
-
-    python "$MANAGE_FILE" collectstatic --noinput --traceback 2>&1 | tee "$COLLECTSTATIC_LOG" | sed '/^Post-processed/d;/^Copying/d;/^$/d' | indent
-    COLLECTSTATIC_STATUS="${PIPESTATUS[0]}"
-
-    set -e
-
-    # Display a warning if collectstatic failed.
-    [ "$COLLECTSTATIC_STATUS" -ne 0 ] && {
-
-        if grep -q 'SyntaxError' "$COLLECTSTATIC_LOG"; then
-            mcount "failure.collectstatic.syntax-error"
-
-        elif grep -q 'ImproperlyConfigured' "$COLLECTSTATIC_LOG"; then
-            mcount "failure.collectstatic.improper-configuration"
-
-        elif grep -q 'The CSS file' "$COLLECTSTATIC_LOG"; then
-            mcount "failure.collectstatic.fancy-references"
-
-        elif grep -q 'OSError' "$COLLECTSTATIC_LOG"; then
-            mcount "failure.collectstatic.missing-file"
-
-        else
-            mcount "failure.collectstatic.other"
-        fi
-
-        echo
-        echo " !     Error while running '$ python $MANAGE_FILE collectstatic --noinput'."
-        echo "       See traceback above for details."
-        echo
-        echo "       You may need to update application code to resolve this error."
-        echo "       Or, you can disable collectstatic for this application:"
-        echo
-        echo "          $ heroku config:set DISABLE_COLLECTSTATIC=1"
-        echo
-        echo "       https://devcenter.heroku.com/articles/django-assets"
-
-        # Additionally, dump out the environment, if debug mode is on.
-        if [ "$DEBUG_COLLECTSTATIC" ]; then
-            echo
-            echo "****** Collectstatic environment variables:"
-            echo
-            env | indent
-        fi
-
-        # Abort the build.
-        exit 1
-    }
-
-    echo
+if [[ ! -f "${MANAGE_FILE}" ]]; then
+  puts-step "Skipping Django collectstatic since no manage.py file found."
+  mcount "django.collectstatic.no_manage_py"
+  exit 0
 fi
+
+mcount "django.collectstatic.enabled"
+
+puts-step "$ python $MANAGE_FILE collectstatic --noinput"
+
+PYTHONPATH=${PYTHONPATH:-.}
+export PYTHONPATH
+COLLECTSTATIC_LOG=$(mktemp)
+
+set +e
+python "$MANAGE_FILE" collectstatic --noinput --traceback 2>&1 | tee "$COLLECTSTATIC_LOG" | sed '/^Post-processed/d;/^Copying/d;/^$/d' | indent
+COLLECTSTATIC_STATUS="${PIPESTATUS[0]}"
+set -e
+
+echo
+
+if [[ "${COLLECTSTATIC_STATUS}" == 0 ]]; then
+  exit 0
+fi
+
+# Display a warning if collectstatic failed.
+if grep -q 'SyntaxError' "$COLLECTSTATIC_LOG"; then
+  mcount "failure.collectstatic.syntax-error"
+elif grep -q 'ImproperlyConfigured' "$COLLECTSTATIC_LOG"; then
+  mcount "failure.collectstatic.improper-configuration"
+elif grep -q 'The CSS file' "$COLLECTSTATIC_LOG"; then
+  mcount "failure.collectstatic.fancy-references"
+elif grep -q 'OSError' "$COLLECTSTATIC_LOG"; then
+  mcount "failure.collectstatic.missing-file"
+else
+  mcount "failure.collectstatic.other"
+fi
+
+echo " !     Error while running '$ python $MANAGE_FILE collectstatic --noinput'."
+echo "       See traceback above for details."
+echo
+echo "       You may need to update application code to resolve this error."
+echo "       Or, you can disable collectstatic for this application:"
+echo
+echo "          $ heroku config:set DISABLE_COLLECTSTATIC=1"
+echo
+echo "       https://devcenter.heroku.com/articles/django-assets"
+
+# Additionally, dump out the environment, if debug mode is on.
+if [ "$DEBUG_COLLECTSTATIC" ]; then
+  echo
+  echo "****** Collectstatic environment variables:"
+  echo
+  env | indent
+fi
+
+exit 1
