collectstatic

diff --git a/bin/steps/django b/bin/steps/django
--- a/bin/steps/django
+++ b/bin/steps/django
@@ -48,14 +48,20 @@ except Exception:
 EOF
 
 
-# Compile assets.
+
+
+
+# Collect static files.
 set +e
 echo "-----> Collecting static files"
-OUT=$(python $PROJECT/manage.py collectstatic --noinput )
 
+OUT=$(python $PROJECT/manage.py collectstatic --noinput 2>&1)
+[ $? -ne 0 ] && STATIC_FAILED=1
 
-[ $? -ne 0 ] && {
-  echo " !     Error running manage.py collectstatic. See http://devcenter.heroku.com/articles/django-assets for more info."
-  echo "$OUT" | indent >&2
-}
+if [ "$STATIC_FAILED" ]; then
+    echo " !     Error running manage.py collectstatic. See http://devcenter.heroku.com/articles/django-assets for more info."
+else
+    echo "$OUT" | indent
+fi
+
 set -e
