cleanups

diff --git a/bin/steps/pipenv-python-version b/bin/steps/pipenv-python-version
--- a/bin/steps/pipenv-python-version
+++ b/bin/steps/pipenv-python-version
@@ -4,19 +4,18 @@ if [[ -f $BUILD_DIR/Pipfile ]]; then
 
     if [[ ! -f $BUILD_DIR/runtime.txt ]]; then
         if [[ ! -f Pipfile.lock ]]; then
-            puts-step "Pipfile.lock not found, creating..."
-            /app/.heroku/python/bin/pipenv lock 2> /dev/null
-        fi
+            puts-warn "Pipfile.lock not found!"
+        else
+            set +e
+            PYTHON=$(cat $BUILD_DIR/Pipfile.lock | jq '._meta.requires.python_version' -r) 2>&1 /dev/null
+            set -e
 
-        set +e
-        PYTHON=$(cat $BUILD_DIR/Pipfile.lock | jq '._meta.requires.python_version' -r)
-        set -e
-
-        if [ "$PYTHON" = 2.7 ]; then
-            echo "python-2.7.13" > $BUILD_DIR/runtime.txt
-        fi
-        if [ "$PYTHON" = 3.6 ]; then
-            echo "python-3.6.0" > $BUILD_DIR/runtime.txt
+            if [ "$PYTHON" = 2.7 ]; then
+                echo "python-2.7.13" > $BUILD_DIR/runtime.txt
+            fi
+            if [ "$PYTHON" = 3.6 ]; then
+                echo "python-3.6.0" > $BUILD_DIR/runtime.txt
+            fi
         fi
     fi
 fi
