draft revisions
typo in last doc line

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -3,21 +3,20 @@
 set +e
 runtime-fixer runtime.txt
 
+# IF we're running tests, favor the test-runtime for version
 if [[ -r "$BUILD_DIR/test-runtime.txt" ]]; then
     PYTHON_VERSION=$(cat $BUILD_DIR/test-runtime.txt)
-    echo $PYTHON_VERSION
 else
     PYTHON_VERSION=$(cat runtime.txt)
 fi
+
 # The location of the pre-compiled python binary.
-VENDORED_PYTHON="${VENDOR_URL}runtimes/$PYTHON_VERSION.tar.gz"
-
-if [[ `wget -S --spider 'https://lang-python.s3.amazonaws.com/runtimes/python-3.6.5.tar.gz'  2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then echo "true"; fi
-
+VENDORED_PYTHON="${VENDOR_URL}/runtimes/$PYTHON_VERSION.tar.gz"
 
 if [[ $PYTHON_VERSION =~ ^python-2 ]]; then
     puts-warn "The latest version of Python is $LATEST_3 (you are using $PYTHON_VERSION, which is unsupported)."
     echo "`cat $BIN_DIR/downgrade-doc.txt`"
+    puts-warn "Aborting build."
     exit 1
 else
   if [[ "$PYTHON_VERSION" != "$LATEST_3" ]]; then
@@ -48,11 +47,11 @@ if [ ! "$SKIP_INSTALL" ]; then
     mkdir -p .heroku/python
 
     mcount "version.python.$PYTHON_VERSION"
-    echo "blah"
-    echo "${VENDORED_PYTHON}"
-    if ! curl "${VENDORED_PYTHON}" -s | tar zxv -C .heroku/python &> /dev/null; then
+
+    if ! curl "${VENDORED_PYTHON}" -s | tar -xvz -C .heroku/python &> /dev/null; then
       puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
       echo "`cat $BIN_DIR/downgrade-doc.txt`"
+      puts-warn "Aborting build."
       exit 1
     fi
 
@@ -64,19 +63,22 @@ if [ ! "$SKIP_INSTALL" ]; then
   hash -r
 fi
 
-# If Pip isn't up to date:
-if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_UPDATE* ]]; then
+# Wrap this call to pip-install in a check to isolate from python_test's effects
+if [[ ! -e "$BUILD_DIR/test-runtime.txt" ]]; then
+    # If Pip isn't up to date:
+    if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_UPDATE* ]]; then
 
-  puts-step "Installing pip"
+      puts-step "Installing pip"
 
-  # Remove old installations.
-  rm -fr /app/.heroku/python/lib/python*/site-packages/pip-*
-  rm -fr /app/.heroku/python/lib/python*/site-packages/setuptools-*
+      # Remove old installations.
+      rm -fr /app/.heroku/python/lib/python*/site-packages/pip-*
+      rm -fr /app/.heroku/python/lib/python*/site-packages/setuptools-*
 
-  /app/.heroku/python/bin/python "$ROOT_DIR/vendor/get-pip.py" pip=="$PIP_UPDATE" &> /dev/null
-  /app/.heroku/python/bin/pip install "$ROOT_DIR/vendor/setuptools-39.0.1-py2.py3-none-any.whl" &> /dev/null
-
+      /app/.heroku/python/bin/python "$ROOT_DIR/vendor/get-pip.py" pip=="$PIP_UPDATE" &> /dev/null
+      /app/.heroku/python/bin/pip install "$ROOT_DIR/vendor/setuptools-39.0.1-py2.py3-none-any.whl" &> /dev/null
+    fi
+else
+    exit 0
 fi
-
 set -e
 hash -r
