Enable remaining optional Shellcheck rules (#1654)
In #1596 a number of optional Shellcheck rules were enabled.
However, there were some which were deferred due to the
number of fixes required, and so were left disabled via the
`.shellcheckrc` file.

In order that we can get the benefit of these rules for new code,
I've removed the global disabling in favour of per file or per line
`disable` directives (and in some cases, fixing outright). These
can then be fixed piecemeal as refactorings occur later.

Of note, one of these optional Shellcheck rules (SC2311) would
have saved me a fair amount of debugging time earlier today in
the new Python version handling implementation.

GUS-W-16898648.

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -1,4 +1,8 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2154 # TODO: Env var is referenced but not assigned.
+# shellcheck disable=SC2250 # TODO: Use braces around variable references even when not strictly required.
+
+set -euo pipefail
 
 PYTHON_VERSION=$(cat runtime.txt)
 # Remove leading and trailing whitespace. Note: This implementation relies upon
@@ -113,6 +117,7 @@ if [[ "$STACK" != "$CACHED_PYTHON_STACK" ]]; then
 fi
 
 if [[ -f .heroku/python-version ]]; then
+	# shellcheck disable=SC2312 # TODO: Invoke this command separately to avoid masking its return value.
 	if [[ ! "$(cat .heroku/python-version)" == "$PYTHON_VERSION" ]]; then
 		puts-step "Python version has changed from $(cat .heroku/python-version) to ${PYTHON_VERSION}, clearing cache"
 		rm -rf .heroku/python
