Revert "update get-pip to look for sha"
This reverts commit a2f3ff7a353a3e9266b79f45a403fff3f43669c3.

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -101,17 +101,10 @@ fi
 # https://github.com/pypa/get-pip
 GETPIP="https://lang-python.s3.amazonaws.com/etc/get-pip.py"
 
-# Grab SHA from get-pip
-CHECK_SHA="$(curl -s "$GETPIP" | sha256sum | cut -d ' ' -f 1)"
-
-# validate the sha is the same one we want
-if [ ! "$CHECK_SHA" == "$GETPIP_SHA" ]; then
-  mcount "failure.python.get-pip.wrong-sha"
-  echo "Incorrect SHA found"
-  exit 1
-else
-  curl "$GETPIP" -o "$ROOT_DIR/get-pip.py"
-  mcount "python.get-pip.install"
+if ! curl "${GETPIP}" -o "$ROOT_DIR/get-pip.py"; then
+    mcount "failure.python.get-pip"
+    echo "Failed to pull down get-pip"
+    exit 1
 fi
 
 # If Pip isn't up to date:
@@ -123,7 +116,7 @@ if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_UPDATE* ]]; then
   rm -fr /app/.heroku/python/lib/python*/site-packages/pip-*
   rm -fr /app/.heroku/python/lib/python*/site-packages/setuptools-*
 
-  /app/.heroku/python/bin/python "$ROOT_DIR/get-pip.py" pip=="$PIP_UPDATE" #&> /dev/null
+  /app/.heroku/python/bin/python "$ROOT_DIR/get-pip.py" pip=="$PIP_UPDATE" &> /dev/null
   /app/.heroku/python/bin/pip install "$ROOT_DIR/vendor/setuptools-39.0.1-py2.py3-none-any.whl" &> /dev/null
 fi
 
