Always output the Python version used and reason why (#1196)
Previously the Python version used for the build was only output to the
log if Python was being installed for the first time, or if the cache
had been invalidated due to stack/Python version/dependency changes.

This meant in the majority of app builds, the Python version was not
shown. This makes debugging harder, as well as the "your Python
version is out of date" warnings less useful, since they don't actually
say what the current version is.

In addition, the reason a Python version was chosen was not explained,
which could be particularly confusing given the "sticky"/cached version
behaviour.

For example, if an existing app that doesn't specify a Python version is
upgraded to a newer stack, the build can fail with a "runtime not available"
error, but no indication as to why that version was chosen. eg:
https://heroku.support/955565
https://heroku.support/958240

Now, the Python version chosen and the reason for that choice is always
output to the build log.

This is becoming particularly relevant given many apps are upgrading to
Heroku-20, which being a newer stack, doesn't have all of the older
runtime versions.

Closes GUS-W-8065925.

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -95,7 +95,7 @@ fi
 
 if [ -f .heroku/python-version ]; then
   if [ ! "$(cat .heroku/python-version)" = "$PYTHON_VERSION" ]; then
-      puts-step "Found $(cat .heroku/python-version), removing"
+      puts-step "Python version has changed from $(cat .heroku/python-version) to ${PYTHON_VERSION}, clearing cache"
       rm -rf .heroku/python
   else
     SKIP_INSTALL=1
@@ -121,17 +121,19 @@ else
   fi
 fi
 
-if [ ! "$SKIP_INSTALL" ]; then
-    puts-step "Installing $PYTHON_VERSION"
+if [[ -n "${SKIP_INSTALL}" ]]; then
+  puts-step "Using cached install of ${PYTHON_VERSION}"
+else
+  puts-step "Installing ${PYTHON_VERSION}"
 
-    # Prepare destination directory.
-    mkdir -p .heroku/python
+  # Prepare destination directory.
+  mkdir -p .heroku/python
 
-    if ! curl "${VENDORED_PYTHON}" -s | tar zxv -C .heroku/python &> /dev/null; then
-      puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
-      puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
-      exit 1
-    fi
+  if ! curl "${VENDORED_PYTHON}" -s | tar zxv -C .heroku/python &> /dev/null; then
+    puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
+    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+    exit 1
+  fi
 
   # Record for future reference.
   echo "$PYTHON_VERSION" > .heroku/python-version
