Implement `bin/report` (#1597)
Implements the `bin/report` build report API, as a replacement for log
based metrics (which stopped working some time ago with the change in
internal observability vendor).

This will help with varies upcoming Python buildpack changes, such as the
EOL of Python 3.8, assessing usage levels of different package managers
(wrt Poetry addition, and future of Pipenv for CNB), removal of the legacy
sqlite feature etc.

This implementation is based on that used by the Node.js buildpack, which
is currently the only buildpack that implements `bin/report`. There are a
number of rough edges with the Node.js implementation that in an ideal
world we'd improve upon. However, given that that implementation works,
is actively used in production, and CNBs are our priority moving forwards,
I've chosen not to make many changes to that design.

See:
https://github.com/heroku/heroku-buildpack-nodejs/blob/main/bin/report
https://github.com/heroku/heroku-buildpack-nodejs/blob/main/lib/metadata.sh
https://github.com/heroku/heroku-buildpack-nodejs/blob/main/lib/kvstore.sh

GUS-W-8047826.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,3 +54,20 @@ jobs:
       - name: Run Hatchet integration tests
         # parallel_split_test runs rspec in parallel, with concurrency equal to PARALLEL_SPLIT_TEST_PROCESSES.
         run: bundle exec parallel_split_test spec/hatchet/
+
+  container-test:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        # Work around lack of TTY causing errors when using `docker run -it`:
+        # https://github.com/actions/runner/issues/241
+        shell: 'script -q -e -c "bash -eo pipefail {0}"'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      # These test both the local development `make run` workflow and that `bin/report` completes successfully
+      # for both passing and failing builds (since `bin/report` can't easily be tested via Hatchet tests).
+      - name: Run buildpack using default app fixture
+        run: make run
+      - name: Run buildpack using an app fixture that's expected to fail
+        run: make run FIXTURE=spec/fixtures/python_version_invalid/
