merge latest upstream as of 8/19/24
- We need to update the stack to heroku-24. The latest changes include support for it.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,7 +12,7 @@ permissions:
 
 jobs:
   lint:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -20,26 +20,27 @@ jobs:
         uses: ruby/setup-ruby@v1
         with:
           bundler-cache: true
-          ruby-version: "3.1"
+          ruby-version: "3.3"
       - name: Run ShellCheck
         run: make lint-scripts
       - name: Run Rubocop
         run: bundle exec rubocop
 
   integration-test:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     strategy:
       fail-fast: false
       matrix:
-        stack: ["heroku-20", "heroku-22"]
+        stack: ["heroku-20", "heroku-22", "heroku-24"]
     env:
       HATCHET_APP_LIMIT: 200
       HATCHET_DEFAULT_STACK: ${{ matrix.stack }}
-      HATCHET_RETRIES: 2
+      HATCHET_EXPENSIVE_MODE: 1
       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
       HEROKU_API_USER: ${{ secrets.HEROKU_API_USER }}
       HEROKU_DISABLE_AUTOUPDATE: 1
       PARALLEL_SPLIT_TEST_PROCESSES: 60
+      RSPEC_RETRY_RETRY_COUNT: 3
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -47,9 +48,26 @@ jobs:
         uses: ruby/setup-ruby@v1
         with:
           bundler-cache: true
-          ruby-version: "3.1"
+          ruby-version: "3.3"
       - name: Hatchet setup
         run: bundle exec hatchet ci:setup
       - name: Run Hatchet integration tests
         # parallel_split_test runs rspec in parallel, with concurrency equal to PARALLEL_SPLIT_TEST_PROCESSES.
         run: bundle exec parallel_split_test spec/hatchet/
+
+  container-test:
+    runs-on: ubuntu-24.04
+    defaults:
+      run:
+        # Work around lack of TTY causing errors when using `docker run -it`:
+        # https://github.com/actions/runner/issues/241
+        shell: 'script -q -e -c "bash -eo pipefail {0}"'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      # These test both the local development `make run` workflow and that `bin/report` completes successfully
+      # for both passing and failing builds (since `bin/report` can't easily be tested via Hatchet tests).
+      - name: Run buildpack using default app fixture
+        run: make run
+      - name: Run buildpack using an app fixture that's expected to fail
+        run: make run FIXTURE=spec/fixtures/python_version_invalid/
diff --git a/bin/og_compile b/bin/og_compile
--- a/bin/og_compile
+++ b/bin/og_compile
@@ -1,38 +1,32 @@
 #!/usr/bin/env bash
+# Usage: bin/compile <build-dir> <cache-dir> <env-dir>
+# See: https://devcenter.heroku.com/articles/buildpack-api
 
-# The Heroku Python Buildpack. This script accepts parameters for a build
-# directory, a cache directory, and a directory for app environment variables.
-
-# Warning: there are a few hacks in this script to accommodate excellent builds
-# on Heroku. No guarantee for external compatibility is made. However,
-# everything should work fine outside of the Heroku environment, if the
-# environment is setup correctly.
-
-# Usage:
-#
-#     $ bin/compile <build-dir> <cache-dir> <env-path>
-
-# Fail fast and fail hard.
 set -eo pipefail
 
-# Used by buildpack-stdlib's metrics features.
-export BPLOG_PREFIX="buildpack.python"
-export BUILDPACK_LOG_FILE=${BUILDPACK_LOG_FILE:-/dev/null}
+[[ -n "$BUILDPACK_XTRACE" ]] && set -o xtrace
 
-[ "$BUILDPACK_XTRACE" ] && set -o xtrace
+BUILD_DIR="${1}"
+CACHE_DIR="${2}"
+ENV_DIR="${3}"
+
+# The absolute path to the root of the buildpack.
+BUILDPACK_DIR=$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" && pwd)
+
+source "${BUILDPACK_DIR}/bin/utils"
+source "${BUILDPACK_DIR}/lib/metadata.sh"
+
+compile_start_time=$(nowms)
+
+# Initialise metadata store.
+meta_init "${CACHE_DIR}" "python"
+meta_setup
 
 # Prepend proper path for old-school virtualenv hackery.
-# This may not be neccessary.
+# This may not be necessary.
 export PATH=:/usr/local/bin:$PATH
 
-# Setup Path variables, for later use in the Buildpack.
-BIN_DIR=$(cd "$(dirname "$0")"; pwd) # absolute path
-ROOT_DIR=$(dirname "$BIN_DIR")
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
-
-# Export Path variables, for use in sub-scripts.
+# Exported for use in subshells, such as the steps run via sub_env.
 export BUILD_DIR CACHE_DIR ENV_DIR
 
 # Set the base URL for downloading buildpack assets like Python runtimes.
@@ -43,8 +37,7 @@ S3_BASE_URL="${BUILDPACK_S3_BASE_URL:-"https://heroku-buildpack-python.s3.us-eas
 # This has to be exported since it's used by the geo-libs step which is run in a subshell.
 
 # Default Python Versions
-# shellcheck source=bin/default_pythons
-source "$BIN_DIR/default_pythons"
+source "${BUILDPACK_DIR}/bin/default_pythons"
 
 # Common Problem Warnings:
 # This section creates a temporary file in which to stick the output of `pip install`.
@@ -52,24 +45,15 @@ source "$BIN_DIR/default_pythons"
 # the user towards resolution of known issues.
 WARNINGS_LOG=$(mktemp)
 
-# The buildpack ships with a few executable tools.
-# This installs them into the path, so we can execute them directly.
-export PATH=$PATH:$ROOT_DIR/vendor/
-
 # Sanitize externally-provided environment variables:
-# The following environment variables are either problematic or simply unneccessary
+# The following environment variables are either problematic or simply unnecessary
 # for the buildpack to have knowledge of, so we unset them, to keep the environment
 # as clean and pristine as possible.
 unset PYTHONHOME PYTHONPATH
 
-# Import the utils script, which contains helper functions used throughout the buildpack.
-# shellcheck source=bin/utils
-source "$BIN_DIR/utils"
-
 # Import the warnings script, which contains the `pip install` user warning mechanisms
 # (mentioned and explained above)
-# shellcheck source=bin/warnings
-source "$BIN_DIR/warnings"
+source "${BUILDPACK_DIR}/bin/warnings"
 
 # Make the directory in which we will create symlinks from the temporary build directory
 # to `/app`.
@@ -77,22 +61,11 @@ source "$BIN_DIR/warnings"
 # More on this topic later.
 mkdir -p /app/.heroku
 
-# This buildpack programatically generates (or simply copies) a number of files for
-# buildpack machinery: an export script, and a number of `.profile.d` scripts. This
-# section declares the locations of those files and targets.
 PROFILE_PATH="$BUILD_DIR/.profile.d/python.sh"
-EXPORT_PATH="$BIN_DIR/../export"
+EXPORT_PATH="${BUILDPACK_DIR}/export"
 GUNICORN_PROFILE_PATH="$BUILD_DIR/.profile.d/python.gunicorn.sh"
 WEB_CONCURRENCY_PROFILE_PATH="$BUILD_DIR/.profile.d/WEB_CONCURRENCY.sh"
 
-# We'll need to send these statics to other scripts we `source`.
-export BUILD_DIR CACHE_DIR BIN_DIR PROFILE_PATH EXPORT_PATH
-
-# Python Environment Variables
-# Set Python-specific environment variables, for running Python within the buildpack.
-# Notes on each variable included.
-
-# PATH is relatively obvious, we need to be able to execute 'python'.
 export PATH=/app/.heroku/python/bin:/app/.heroku/vendor/bin:$PATH
 # Tell Python to not buffer it's stdin/stdout.
 export PYTHONUNBUFFERED=1
@@ -112,10 +85,6 @@ export PKG_CONFIG_PATH=/app/.heroku/vendor/lib/pkg-config:/app/.heroku/python/li
 # Disable pip's warnings about EOL Python since we show our own.
 export PIP_NO_PYTHON_VERSION_WARNING=1
 
-# The Application Code
-# --------------------
-
-# Switch to the repo's context.
 cd "$BUILD_DIR"
 
 # The Cache
@@ -150,46 +119,74 @@ fi
 # This part of the code is used to allow users to customize their build experience
 # without forking the buildpack by providing a `bin/pre_compile` script, which gets
 # run inline with the buildpack automatically.
-
-# shellcheck source=bin/steps/hooks/pre_compile
-source "$BIN_DIR/steps/hooks/pre_compile"
+source "${BUILDPACK_DIR}/bin/steps/hooks/pre_compile"
 
 # Sticky runtimes. If there was a previous build, and it used a given version of Python,
-# continue to use that version of Python in perpituity (warnings will be raised if
-# they are out–of–date).
-if [ -f "$CACHE_DIR/.heroku/python-version" ]; then
+# continue to use that version of Python in perpetuity.
+if [[ -f "$CACHE_DIR/.heroku/python-version" ]]; then
   CACHED_PYTHON_VERSION=$(cat "$CACHE_DIR/.heroku/python-version")
 fi
 
 # We didn't always record the stack version. This code is in place because of that.
-if [ -f "$CACHE_DIR/.heroku/python-stack" ]; then
+if [[ -f "$CACHE_DIR/.heroku/python-stack" ]]; then
   CACHED_PYTHON_STACK=$(cat "$CACHE_DIR/.heroku/python-stack")
 else
   CACHED_PYTHON_STACK=$STACK
 fi
 
+# TODO: Move this into a new package manager handling implementation when adding Poetry support.
+# We intentionally don't mention `setup.py` here since it's being removed soon.
+if [[ ! -f requirements.txt && ! -f Pipfile && ! -f setup.py ]]; then
+  puts-warn
+  puts-warn "Error: Couldn't find any supported Python package manager files."
+  puts-warn
+  puts-warn "A Python app on Heroku must have either a 'requirements.txt' or"
+  puts-warn "'Pipfile' package manager file in the root directory of its"
+  puts-warn "source code."
+  puts-warn
+  puts-warn "Currently the root directory of your app contains:"
+  puts-warn
+  # TODO: Overhaul logging helpers so they can handle prefixing multi-line strings, and switch to them.
+  # shellcheck disable=SC2012 # Using `ls` instead of `find` is absolutely fine for this use case.
+  ls -1 --indicator-style=slash "${BUILD_DIR}" | sed 's/^/ !     /'
+  puts-warn
+  puts-warn "If your app already has a package manager file, check that it:"
+  puts-warn
+  puts-warn "1. Is in the top level directory (not a subdirectory)."
+  puts-warn "2. Has the correct spelling (the filenames are case-sensitive)."
+  puts-warn "3. Isn't listed in '.gitignore' or '.slugignore'."
+  puts-warn
+  puts-warn "Otherwise, add a package manager file to your app. If your app has"
+  puts-warn "no dependencies, then create an empty 'requirements.txt' file."
+  puts-warn
+  puts-warn "For help with using Python on Heroku, see:"
+  puts-warn "https://devcenter.heroku.com/articles/getting-started-with-python"
+  puts-warn "https://devcenter.heroku.com/articles/python-support"
+  puts-warn
+  meta_set "failure_reason" "package-manager-not-found"
+  exit 1
+fi
+
 # Pipenv Python version support.
 # Detect the version of Python requested from a Pipfile (e.g. python_version or python_full_version).
 # Convert it to a runtime.txt file.
-
-# shellcheck source=bin/steps/pipenv-python-version
-source "$BIN_DIR/steps/pipenv-python-version"
+source "${BUILDPACK_DIR}/bin/steps/pipenv-python-version"
 
 if [[ -f runtime.txt ]]; then
   # PYTHON_VERSION_SOURCE may have already been set by the pipenv-python-version step.
   # TODO: Refactor this and stop pipenv-python-version using runtime.txt as an API.
   PYTHON_VERSION_SOURCE=${PYTHON_VERSION_SOURCE:-"runtime.txt"}
   puts-step "Using Python version specified in ${PYTHON_VERSION_SOURCE}"
-  mcount "version.reason.python.specified"
+  meta_set "python_version_reason" "specified"
 elif [[ -n "${CACHED_PYTHON_VERSION:-}" ]]; then
   puts-step "No Python version was specified. Using the same version as the last build: ${CACHED_PYTHON_VERSION}"
   echo "       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes"
-  mcount "version.reason.python.cached"
+  meta_set "python_version_reason" "cached"
   echo "${CACHED_PYTHON_VERSION}" > runtime.txt
 else
   puts-step "No Python version was specified. Using the buildpack default: ${DEFAULT_PYTHON_VERSION}"
   echo "       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes"
-  mcount "version.reason.python.default"
+  meta_set "python_version_reason" "default"
   echo "${DEFAULT_PYTHON_VERSION}" > runtime.txt
 fi
 
@@ -199,7 +196,7 @@ mkdir -p "$(dirname "$PROFILE_PATH")"
 mkdir -p /app/.heroku/src
 
 # On Heroku CI, builds happen in `/app`. Otherwise, on the Heroku platform,
-# they occur in a temp directory. Beacuse Python is not portable, we must create
+# they occur in a temp directory. Because Python is not portable, we must create
 # symlinks to emulate that we are operating in `/app` during the build process.
 # This is (hopefully obviously) because apps end up running from `/app` in production.
 # Realpath is used to support use-cases where one of the locations is a symlink to the other.
@@ -213,44 +210,41 @@ fi
 
 # Download / Install Python, from pre-build binaries available on Amazon S3.
 # This step also bootstraps pip / setuptools.
-(( start=$(nowms) ))
-# shellcheck source=bin/steps/python
-source "$BIN_DIR/steps/python"
-mtime "python.install.time" "${start}"
+install_python_start_time=$(nowms)
+source "${BUILDPACK_DIR}/bin/steps/python"
+meta_time "python_install_duration" "${install_python_start_time}"
 
 # Install Pipenv dependencies, if a Pipfile was provided.
-# shellcheck source=bin/steps/pipenv
-source "$BIN_DIR/steps/pipenv"
+source "${BUILDPACK_DIR}/bin/steps/pipenv"
 
 # If no requirements.txt file given, assume `setup.py develop` is intended.
 # This allows for people to ship a setup.py application to Heroku
 
-if [ ! -f requirements.txt ] && [ ! -f Pipfile ]; then
+if [[ ! -f requirements.txt ]] && [[ ! -f Pipfile ]]; then
+  meta_set "setup_py_only" "true"
   echo "-e ." > requirements.txt
+else
+  meta_set "setup_py_only" "false"
 fi
 
 # SQLite3 support.
 # This sets up and installs sqlite3 dev headers and the sqlite3 binary but not the
 # libsqlite3-0 library since that exists on the stack image.
-(( start=$(nowms) ))
-# shellcheck source=bin/steps/sqlite3
-source "$BIN_DIR/steps/sqlite3"
+install_sqlite_start_time=$(nowms)
+source "${BUILDPACK_DIR}/bin/steps/sqlite3"
 buildpack_sqlite3_install
-mtime "sqlite3.install.time" "${start}"
+meta_time "sqlite_install_duration" "${install_sqlite_start_time}"
 
 # pip install
 # -----------
 
 # Install dependencies with pip (where the magic happens).
-(( start=$(nowms) ))
-# shellcheck source=bin/steps/pip-install
-source "$BIN_DIR/steps/pip-install"
-mtime "pip.install.time" "${start}"
+source "${BUILDPACK_DIR}/bin/steps/pip-install"
 
 # Support for NLTK corpora.
-(( start=$(nowms) ))
-sub_env "$BIN_DIR/steps/nltk"
-mtime "nltk.download.time" "${start}"
+nltk_downloader_start_time=$(nowms)
+sub_env "${BUILDPACK_DIR}/bin/steps/nltk"
+meta_time "nltk_downloader_duration" "${nltk_downloader_start_time}"
 
 # Support for editable installations. Here, we are copying pip–created src directory,
 # and copying it into the proper place (the logical place to do this was early, but it must be done here).
@@ -267,12 +261,12 @@ fi
 # This is the cause for the majority of build failures on the Python platform.
 # These failures are intentional — if collectstatic (which can be tricky, at times) fails,
 # your build fails.
-(( start=$(nowms) ))
-sub_env "$BIN_DIR/steps/collectstatic"
-mtime "collectstatic.time" "${start}"
+collectstatic_start_time=$(nowms)
+sub_env "${BUILDPACK_DIR}/bin/steps/collectstatic"
+meta_time "django_collectstatic_duration" "${collectstatic_start_time}"
 
 
-# Progamatically create .profile.d script for application runtime environment variables.
+# Programmatically create .profile.d script for application runtime environment variables.
 
 # Set the PATH to include Python / pip / pipenv / etc.
 set_env PATH "\$HOME/.heroku/python/bin:\$PATH"
@@ -310,12 +304,11 @@ EOT
 fi
 
 # Install sane-default script for $WEB_CONCURRENCY and $FORWARDED_ALLOW_IPS.
-cp "$ROOT_DIR/vendor/WEB_CONCURRENCY.sh" "$WEB_CONCURRENCY_PROFILE_PATH"
-cp "$ROOT_DIR/vendor/python.gunicorn.sh" "$GUNICORN_PROFILE_PATH"
+cp "${BUILDPACK_DIR}/vendor/WEB_CONCURRENCY.sh" "$WEB_CONCURRENCY_PROFILE_PATH"
+cp "${BUILDPACK_DIR}/vendor/python.gunicorn.sh" "$GUNICORN_PROFILE_PATH"
 
 # Experimental post_compile hook. Don't remove this.
-# shellcheck source=bin/steps/hooks/post_compile
-source "$BIN_DIR/steps/hooks/post_compile"
+source "${BUILDPACK_DIR}/bin/steps/hooks/post_compile"
 
 # Store new artifacts in the cache.
 rm -rf "$CACHE_DIR/.heroku/python"
@@ -332,6 +325,4 @@ if [[ -d .heroku/src ]]; then
   cp -R .heroku/src "$CACHE_DIR/.heroku/" &> /dev/null || true
 fi
 
-# Measure the size of the Python installation.
-# shellcheck disable=SC2119
-mmeasure 'python.size' "$(measure-size)"
+meta_time "total_duration" "${compile_start_time}"
diff --git a/bin/steps/sqlite3 b/bin/steps/sqlite3
--- a/bin/steps/sqlite3
+++ b/bin/steps/sqlite3
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-# shellcheck source=bin/utils
-source "$BIN_DIR/utils"
+# TODO: Remove this entirely since the Python stdlib now includes modern sqlite support,
+# and the APT buildpack should be used if an app needs the sqlite CLI/headers.
 
 sqlite3_install() {
   HEROKU_PYTHON_DIR="$1"
@@ -15,16 +15,18 @@ sqlite3_install() {
   mkdir -p "$APT_CACHE_DIR/archives/partial"
   mkdir -p "$APT_STATE_DIR/lists/partial"
 
-  APT_OPTIONS="-o debug::nolocking=true"
-  APT_OPTIONS="$APT_OPTIONS -o dir::cache=$APT_CACHE_DIR"
-  APT_OPTIONS="$APT_OPTIONS -o dir::state=$APT_STATE_DIR"
-  APT_OPTIONS="$APT_OPTIONS -o dir::etc::sourcelist=/etc/apt/sources.list"
+  APT_OPTIONS=(
+    "--option=debug::nolocking=true"
+    "--option=dir::cache=${APT_CACHE_DIR}"
+    "--option=dir::state=${APT_STATE_DIR}"
+    "--option=dir::etc::sourcelist=/etc/apt/sources.list"
+  )
 
-  apt-get $APT_OPTIONS update > /dev/null 2>&1
-  if [ -z "$HEADERS_ONLY" ]; then
-    apt-get $APT_OPTIONS -y -d --reinstall install libsqlite3-dev sqlite3 > /dev/null 2>&1
+  apt-get "${APT_OPTIONS[@]}" update > /dev/null 2>&1
+  if [[ -z "$HEADERS_ONLY" ]]; then
+    apt-get "${APT_OPTIONS[@]}" -y -d --reinstall install libsqlite3-dev sqlite3 > /dev/null 2>&1
   else
-    apt-get $APT_OPTIONS -y -d --reinstall install libsqlite3-dev
+    apt-get "${APT_OPTIONS[@]}" -y -d --reinstall install libsqlite3-dev
   fi
 
   find "$APT_CACHE_DIR/archives/" -name "*.deb" -exec dpkg -x {} "$HEROKU_PYTHON_DIR/sqlite3/" \;
@@ -38,16 +40,19 @@ sqlite3_install() {
   rm -f "$HEROKU_PYTHON_DIR/lib/pkgconfig/sqlite3.pc"
   rm -f "$HEROKU_PYTHON_DIR/bin/sqlite3"
 
+  # eg: `x86_64` or `aarch64`
+  GNU_ARCH=$(arch)
+
   # copy over sqlite3 headers & bins and setup linking against the stack image library
   mv "$HEROKU_PYTHON_DIR/sqlite3/usr/include/"* "$HEROKU_PYTHON_DIR/include/"
-  mv "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/x86_64-linux-gnu"/libsqlite3.*a "$HEROKU_PYTHON_DIR/lib/"
+  mv "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu"/libsqlite3.*a "$HEROKU_PYTHON_DIR/lib/"
   mkdir -p "$HEROKU_PYTHON_DIR/lib/pkgconfig"
   # set the right prefix/lib directories
-  sed -e 's/prefix=\/usr/prefix=\/app\/.heroku\/python/' -e 's/\/x86_64-linux-gnu//' "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc" > "$HEROKU_PYTHON_DIR/lib/pkgconfig/sqlite3.pc"
+  sed -e 's/prefix=\/usr/prefix=\/app\/.heroku\/python/' -e "s/\/${GNU_ARCH}-linux-gnu//" "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu/pkgconfig/sqlite3.pc" > "$HEROKU_PYTHON_DIR/lib/pkgconfig/sqlite3.pc"
   # need to point the libsqlite3.so to the stack image library for /usr/bin/ld -lsqlite3
-  SQLITE3_LIBFILE="/usr/lib/x86_64-linux-gnu/$(readlink -n "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/x86_64-linux-gnu/libsqlite3.so")"
+  SQLITE3_LIBFILE="/usr/lib/${GNU_ARCH}-linux-gnu/$(readlink -n "$HEROKU_PYTHON_DIR/sqlite3/usr/lib/${GNU_ARCH}-linux-gnu/libsqlite3.so")"
   ln -s "$SQLITE3_LIBFILE" "$HEROKU_PYTHON_DIR/lib/libsqlite3.so"
-  if [ -z "$HEADERS_ONLY" ]; then
+  if [[ -z "$HEADERS_ONLY" ]]; then
     mv "$HEROKU_PYTHON_DIR/sqlite3/usr/bin"/* "$HEROKU_PYTHON_DIR/bin/"
   fi
 
@@ -57,20 +62,18 @@ sqlite3_install() {
 }
 
 buildpack_sqlite3_install() {
-  HEROKU_PYTHON_DIR="$BUILD_DIR/.heroku/python"
-
-  SQLITE3_VERSION_FILE="$BUILD_DIR/.heroku/python-sqlite3-version"
-  if [ -f "$SQLITE3_VERSION_FILE" ]; then
-    INSTALLED_SQLITE3_VERSION=$(cat "$SQLITE3_VERSION_FILE")
-  fi
-
   puts-step "Installing SQLite3"
 
+  # TODO: This never actual prints failure or even aborts the build, since
+  # the conditional disables `set -e` inside the called function:
+  # https://stackoverflow.com/q/19789102
+  # ...plus whoever wrote this forgot the `exit 1` in the `else` anyway.
   if sqlite3_install "$BUILD_DIR/.heroku/python" ; then
-    mcount "success.python.sqlite3"
+    # mcount "success.python.sqlite3"
+    :
   else
     echo "Sqlite3 failed to install."
-    mcount "failure.python.sqlite3"
+    # mcount "failure.python.sqlite3"
   fi
 
   mkdir -p "$CACHE_DIR/.heroku/"
